/**
 * EngineEvent - Union of all legal events
 * 
 * Rules:
 * - Events are immutable data structures
 * - No event carries calculated values (only raw inputs)
 * - All timestamps must be provided (never generated by engine)
 * - All prices must be provided (never fetched by engine)
 */

export type EngineEvent =
  | OpenPositionEvent
  | ClosePositionEvent
  | UpdatePricesEvent
  | AddFundsEvent
  | RemoveFundsEvent
  | AddBonusEvent
  | RemoveBonusEvent
  | SetStopLossEvent
  | SetTakeProfitEvent
  | CancelPendingPositionEvent
  | UpdateAccountStatusEvent
  | UpdateAccountPoliciesEvent;

// TODO: Import individual event types from event files
// TODO: Add discriminated union helper for type guards
